### ISSUE TITLE
TorrentDay Plugin no longer working . . . 

### ISSUE THREAD

**Issue by defr0st** [Novik/ruTorrent#1073]
Recently tracker site TorrentDay.com has had a variety of changes.

Firstly, due to widespread blockages of many tracker sites in the UK, TorrentDay has sprouted a number of alternative hostings on alternative domain names and IP addresses.

Notably; torrentday.eu.

As of a fortnight or so ago, the site has revamped the look and feel of the site fairly thoroughly ... under the hood many things are similar but a little different, web facing it's very different.

Previously the site had a static page load with a delayed aJax() load of dynamic content as recent torrents were "paged" through, now a complete static page is delivered each time.. cleaner code, no embedded javascript, and the use of fancybox pretty layout scripting in a separate attachment.

So, more modern.

I note, from browsing:
https://github.com/Novik/ruTorrent/blob/master/plugins/extsearch/engines/TorrentDay.php

that line 15 (?) uses a hardcoded URL for the tracker site web interface root:
 www.torrentday.com

The simplest, easiest, least fuss fix for the current "Doesn't work" issue would be to change that to 
www.classic.torrentday.com 

as the site operators have keep the old setup running just as before ( to the best of my knowledge the old 'classic' site is hosted nowhere else.

The somewhat more robust fix for the future would be to grab the page source from the revamped site and redo the line 30 extract all reg. expressions against the new layout, ... with some slight tweaks to the Browse.php?search & other(?) functionality.

An alternative 'fix' ... perhaps preferable overall **should** the torrentday site retain the old interface is to hook into the dynamic content API used by the classic site ... as it directly returns .JSON data streams as per POST request.

The SickRage torrentday plugin uses this approach ( also hosted on GIT ) and that can be done & tested against either 

https://tdonline.org/V3/API/API.php

or against:

https://classic.torrentday.com/V3/API/API.php

( but not: https://torrentday.com/V3/API/API.php )

Cheers.

( PS: I don't use ruTorrent or SickRage etc. myself, I'm not really a webdev kind of person, I'm mainly posting on behalf of other users in the forums who seem to be struggling to correctly nail the issue )

**Comment by Novik** [comment]
> https://tdonline.org/V3/API/API.php
> https://classic.torrentday.com/V3/API/API.php
> ( but not: https://torrentday.com/V3/API/API.php )

"No page exists at your destination address" for all three urls.

**Comment by defr0st** [comment]
Thanks for having a look.

RE; "Sorry .." - I'm not fussed, it's not really a problem for me

Re: ""No page exists at your destination address" for all three urls."
Of course not -- two of them are active .json links that respond to POST requests with auth cookies, and the other one is a formerly active listener that no longer responds as " torrentday.com " now serves static rather than dynamic content.

See: http://lookpic.com/O/i2/1108/PwGNRjcV.png for a terminal screen shot from a few ( ~24 ? hours back )
$tdCookie is a string variable that looks like
"uid=2xXxXx6 ; pass=50xXxXxXxXxXxXxXxXxXxXxX80"

**If** you're interested in an account for debugging I can likely throw you an invite ( usual caveat: if you leech on that account you get kicked <shrug> and it reflects on me <oops:sad face> )

I'm more interested in the *others* from tday showing up that actually use your software ( & a few of them are on staff ) and letting them deal with invites etc. 
I've linked this in the forums .. it's their itch to scratch.

As noted above, the simplest fix would be a one line root URL change to classic.torrentday.com ( where the old HTML your plugin parses still resides ) .. unless you're curious about the .JSON interface ( which really flies by comparison -- it's a no HTML , no pause for dynamic callback , just the damn data of interest call )

Of interest; if you haven't seen it:
http://stedolan.github.io/jq/
http://www.compciv.org/recipes/cli/jq-for-parsing-json/

**Comment by domdorn** [comment]
Hi..

sorry to resurrect this old issue. 

I've fixed the torrentday search plugin on my local machine
( https://gist.github.com/domdorn/390f09f953cd111e15b923b77a46104a ) 
@defr0st would be great if you could give it a try ? 

I'm not really sure about the API Endpoint 
https://tdonline.org/V3/API/API.php
as I can't find any documentation about it and the parameters look kind of odd to me. If you can provide me with documentation, I can change the plugin to use the API Endpoint instead. 

cheers

**Comment by VilDegard** [comment]
Hi @domdorn 

I tried your repo to fix torrentday extsearch but it still doesn't work on my server.
Could you check again if it works for you? Any alternatives to propose?

Thanks for your work

**Comment by VilDegard** [comment]
Any help please?

**Comment by domdorn** [comment]
@VilDegard 
- did you replace the TorrentDay.php file ? 
- did you enter your cookie in the cookies section of the settings?
![image](https://cloud.githubusercontent.com/assets/100349/22646569/54c7fb82-ec6d-11e6-92a0-1330ce4eb315.png)

**Comment by VilDegard** [comment]
@domdorn 
Yes I did, exactly as you said.
As mentioned in the previous edited post, I get some searches, but they are like old references, back to 2015 can not go over 2016, even for very recent release searches.

How can I fix this please?

**Comment by domdorn** [comment]
hmm... sounds like a sorting issue.. seen that recently too.. 
from a quick look, it looks like its sorting on seeds. try changing the sort parameter on line 134 to 6
sort=6&type=desc

that way it would/should sort by added date (I think.. not sure though). 

would be great if you could play a little with the parameter(s) and report your findings.. you can also just add it to manual searches on the website..

**Comment by domdorn** [comment]
@VilDegard did you try my suggestion? does it work for you now?

**Comment by VilDegard** [comment]
@domdorn I put "&sort=6&type=desc" and even "&cata=yes". Not working. Any suggestions?

**Comment by VilDegard** [comment]
@domdorn ? Any suggestions please? Did I do something wrong on the script?

**Comment by domdorn** [comment]
please provide me with a searchterm where you experience different results on the website than with the plugin..

**Comment by VilDegard** [comment]
@domdorn thanks for your help man, much appreciated.

Link : https://s12.postimg.org/on5ym3xsb/Screen_Shot_2017_02_12_at_17_58_49.png

By the way, when I'm highlighting a results, I have a huge list of other results in the description. Very weird.

**Comment by domdorn** [comment]
@VilDegard please write me a email, you find my address on my profile page.

**Comment by VilDegard** [comment]
@domdorn done. Waiting for your reply. Thanks

**Comment by domdorn** [comment]
https://github.com/Novik/ruTorrent/pull/1409
