### ISSUE TITLE
Unpack Not Working

### ISSUE THREAD

**Issue by Heardy92** [Novik/ruTorrent#1199]
By the looks of it, unpack doesn't seem to want to automatically unpack the downloaded torrents on ruTorrent, I can do it manually but not automatically. The only problem with doing it manually is even changing the file destination doesn't work as they still get unpacked to the folder they were originally in.

I'm using the latest unpack as well.

Any suggestions?

**Comment by Aealo** [comment]
I have same problem

**Comment by xombiemp** [comment]
What OS are you using so I can try to reproduce the problem?  It works for me on Ubuntu 14.04.

**Comment by Aealo** [comment]
I am using Ubuntu 12.04 and ruTorrent 3.6

**Comment by PreK** [comment]
I have same problem with fresh install on ubuntu 14.04 or debian 8 dont work unrar, auto ou with right click, cannot get any errors or logs if someone wanna help-me debug I apreciate ..

**Comment by xombiemp** [comment]
@Aealo Try using the latest version of ruTorrent from git.

@PreK It is probably some configuration problem because it works for me.  Are you using the latest ruTorrent from Git?  Do you have unrar installed? What does it say in the plugins tab next to the unpack plugin?

**Comment by PreK** [comment]
yes i have rutorrent from git and have unrar instaled and plugin say Loaded and instaled

**Comment by Heardy92** [comment]
I'm using Mac so El Capitan 10.11.2  and running it on a seedbox ruTorrent version 3.6.

**Comment by xombiemp** [comment]
I will try a fresh install of Ubuntu 14.04 and the latest rutorrent.

**Comment by xombiemp** [comment]
Just tested with a fresh install of Ubuntu 14.04 and the rutorrent from git.  Auto unrar works great!  Did you enable auto unrar in the settings?
![screen shot 2016-02-20 at 6 09 37 pm](https://cloud.githubusercontent.com/assets/690710/13200254/34c17136-d7fd-11e5-8d8b-6cc29432d363.png)

**Comment by Heardy92** [comment]
I've made sure it's enabled in the settings, yeah. Still unsure why it's not working.

**Comment by Heardy92** [comment]
Manual unpack works fine, it's just the automatic unpack doesn't work at all.

**Comment by Aealo** [comment]
Mine is working now, not sure if restart or installing autotools helped

**Comment by xombiemp** [comment]
@Heardy92 In my testing it seems that you must restart rtorrent after you enable auto unpacking in the rutorrent settings before it will work.  That's probably why @Aealo 's started working after he restarted.  Try to restart rtorrent after you enable auto unpacking and then let me know what happens.

**Comment by Novik** [comment]
> In my testing it seems that you must restart rtorrent after you enable auto unpacking 

This was fixed.

**Comment by Heardy92** [comment]
I've tried restarting and it still doesn't work on there. Manual works fine it's just the automatic, Autotools don't work either for me.

**Comment by PreK** [comment]
for me dont work manual ou automatic ... debian 8 here

**Comment by johnpowell** [comment]
Same here on Ubuntu 14.04. Manual works as intended but automatic fails.

**Comment by viper151** [comment]
I have the exact same issue.Is there a log file for this so I could check for any errors?

**Comment by C74K** [comment]
how to fix it ??

**Comment by xnaas** [comment]
Also checking in with automatic never kicking in (yes, I did reboot) but manual working just fine.

**Comment by pguizeline** [comment]
Hi, anyone figured this one out? My current install is Debian Jessie, with ruTorrent 3.7, the right click manual unpack works, but the auto unpack does not. I have the tick box checked and the regex is set with "/.*/".

Thanks in advance for any help!

**Comment by Seeder101** [comment]
Hi guys...I know this a known issue already but my fix was to downgrade the unpack plugin to 3.5 and that made it work just fine...just replace the new one with the old one (3.5) and you're set

hope that helps in any way 

NOTE: I didn't make a restart to the rtorrent after checking the "autounpacking" as it stated in @xombiemp comment! because of @Novik reply

**Comment by From2750** [comment]
Is it possible to use Macros when its uncheck ?
I use macros in autodl-irssi and its would be very nice is unpack could understand macros like this

$(Name1)/Season-$(Season)

**Comment by marcocm** [comment]
where do I found the plugins folder to replace the 3.7 unpack version with the 3.5 ? I'm using a qnap nas and I don't find the folder...

**Comment by j2m2** [comment]
Hi guys! Unpack is not working for me. If I do unpack from rutorrent the output is "Failed" 

This is my unrar help
# /usr/bin/unrar --help
Usage: unrar [OPTION...] ARCHIVE [FILE...] [DESTINATION]
Extract files from rar archives.

  -x, --extract              Extract files from archive (default)
  -t, --list                 List files in archive
  -f, --force                Overwrite files when extracting
      --extract-newer        Only extract newer files from the archive
      --extract-no-paths     Don't create directories while extracting
  -p, --password             Decrypt archive using a password
  -?, --help                 Give this help list
      --usage                Give a short usage message
  -V, --version              Print program version

In conf.php
$pathToExternals['unzip'] = '/usr/bin/unzip'; 
$pathToExternals['unrar'] = '/usr/bin/unrar';

**Comment by tkirkland** [comment]
That command line output is from the package 'unrar-free.'  It is not the same as the 'unrar' package that is the same as unrar from the RAR developer.  You're getting the errors because the free version has different switches so unpacking fails.

**Comment by savahu** [comment]
I still have issues with this.
Manual unpacking works but autounpacking fails.
Is there any logging that I can check?

My autounpacking settings are as follows (default):
![image](https://user-images.githubusercontent.com/14197530/54524344-088bf480-4972-11e9-9b93-c47ce497fbb6.png)

**Comment by Novik** [comment]
> Is there any logging that I can check?

Check plugin's conf.php, variable $unpack_debug_enabled.
Diagnostic will be written to the file, specified in the main config.php. By default /tmp/errors.log.

**Comment by whytedwarf** [comment]
I have the same problem. I'm able to manual extract but auto does not work. I checked for the errors.log file and it does not exist. Any other suggestions would be appreciated.

**Comment by savahu** [comment]
> > Is there any logging that I can check?
> 
> Check plugin's conf.php, variable $unpack_debug_enabled.
> Diagnostic will be written to the file, specified in the main config.php. By default /tmp/errors.log.
Thanks for your reply.
I have set `$unpack_debug_enabled = true;` in ruTorrent/plugins/unpack/conf.php.
In the ruTorrent config.php I have 
`$do_diagnostic = true;
$log_file = '/tmp/errors.log';`
Yet the file /tmp/errors.log is empty and nothing is logged.

**Comment by savahu** [comment]
Any idea how to further investigate this?

**Comment by whytedwarf** [comment]
I was finally able to get an error.log to work. I'm not sure if there is anything useful.
`
[03.04.19 22:00:02] <?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>system.multicall</methodName><params><param><value><array><data>
<value><struct><member><name>methodName</name><value><string>get_up_total</string></value></member><member><name>params</name><value><array><data>
</data></array></value></member></struct></value>
<value><struct><member><name>methodName</name><value><string>get_down_total</string></value></member><member><name>params</name><value><array><data>
</data></array></value></member></struct></value>
<value><struct><member><name>methodName</name><value><string>d.multicall</string></value></member><member><name>params</name><value><array><data>
<value><string>main</string></value>
<value><string>d.get_hash=</string></value>
<value><string>d.get_up_total=</string></value>
<value><string>d.get_down_total=</string></value>
</data></array></value></member></struct></value>
</data></array></value></param></params></methodCall>
[03.04.19 22:00:02] Status: 200 OK
Content-Type: text/xml
Content-Length: 812

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<params>
<param><value><array><data>
<value><struct>
<member><name>faultCode</name>
<value><i4>-506</i4></value></member>
<member><name>faultString</name>
<value><string>Method 'get_up_total' not defined</string></value></member>
</struct></value>
<value><struct>
<member><name>faultCode</name>
<value><i4>-506</i4></value></member>
<member><name>faultString</name>
<value><string>Method 'get_down_total' not defined</string></value></member>
</struct></value>
<value><struct>
<member><name>faultCode</name>
<value><i4>-506</i4></value></member>
<member><name>faultString</name>
<value><string>Method 'd.multicall' not defined</string></value></member>
</struct></value>
</data></array></value></param>
</params>
</methodResponse>
`

**Comment by Novik** [comment]
1) This has'nt relation to the unpacking
2) IMHO you use custom modified version of ruTorrent and/or rtorrent. Because native version can't generate such requests.

**Comment by whytedwarf** [comment]
> 1. This has'nt relation to the unpacking
> 2. IMHO you use custom modified version of ruTorrent and/or rtorrent. Because native version can't generate such requests.

I'm using the Manjaro and rtorrent is from the package repository and rutorrent is from AUR and is pulled directly from github without any modifications other than added themes and plugins.

**Comment by xombiemp** [comment]
I use Archlinux and my rtorrent is also from the repository https://www.archlinux.org/packages/community/x86_64/rtorrent/
and rutorrent is from git (not using AUR).
Also unzip and rar are from the following:
https://www.archlinux.org/packages/extra/x86_64/unzip/
https://aur.archlinux.org/packages/rar/

So our setups sound like they are very similar.  Auto unpack works as expected for me.  I'll attach a few settings so you can compare:
<img width="593" alt="Screen Shot 2019-04-04 at 9 07 46 AM" src="https://user-images.githubusercontent.com/690710/55566548-26b75b80-56b9-11e9-9a55-ab4c3b3af7ed.png">

```
<?php

@define('USE_UNZIP', true, true);
@define('USE_UNRAR', true, true);

$pathToExternals['unzip'] = '';		// Something like /usr/bin/unzip. If empty, will be found in PATH.
$pathToExternals['unrar'] = '';		// Something like /usr/bin/unrar. If empty, will be found in PATH.

$cleanupAutoTasks = false;		// Remove autounpack tasks parameters after finish, otherwise will be shown in the 'Tasks' tab
$deleteAutoArchives = true;	// Delete archive files after successful auto unpack. Will not remove archives unless AutoMove is enabled and the operation type is not Move.
$unpackToTemp = true;    // During auto upacking, the archive will be unpacked in the $tempDirectory defined in rutorrent/conf/config.php, and then will be moved from there to the final destination.

$unpack_debug_enabled = false;		// set "true" to enable debug output
```

**Comment by whytedwarf** [comment]
Thanks I might just try installing without using AUR. The whole purpose was to make it easier to upgrade, but I guess I could just create a script for that. I followed your guide for installing on Arch except I was unable to get Caddy to run so I used nginx instead.

My settings for unpack are identical in rutorrent. My config is slightly different as I was getting php cannot execute such and such command.
```php
<?php

@define('USE_UNZIP', true, true);
@define('USE_UNRAR', true, true);

$pathToExternals['unzip'] = '/usr/bin/unzip';		// Something like /usr/bin/unzip. If empty, will be found in PATH.
$pathToExternals['unrar'] = '/usr/bin/unrar';		// Something like /usr/bin/unrar. If empty, will be found in PATH.

$cleanupAutoTasks = false;		// Remove autounpack tasks parameters after finish, otherwise will be shown in the 'Tasks' tab
$deleteAutoArchives = false;	// Delete archive files after successful auto unpack. Will not remove archives unless AutoMove is enabled and the operation type is not Move.
$unpackToTemp = false;    // During auto upacking, the archive will be unpacked in the $tempDirectory defined in rutorrent/conf/config.php, and then will be moved from there to the final destination.

$unpack_debug_enabled = false;		// set "true" to enable debug output
```

**Comment by savahu** [comment]
This issue is solved for me.
The cause of my issue was the permissions on the folder where rTorrent downloaded the files.
ruTorrent had no permission to unpack there, because it was running under a different user.

**Comment by whytedwarf** [comment]
> This issue is solved for me.
> The cause of my issue was the permissions on the folder where rTorrent downloaded the files.
> ruTorrent had no permission to unpack there, because it was running under a different user.

I was able to fix my problem by changing the owner of my data directory. I completely forgot to check that until I read your comment. Thank you.

**Comment by jaffa374** [comment]
Just to keep this thread alive, i'm also having this problem. Manual unpack works, auto unpack simply stopped working. I've enabled the logs in the unpack plugin via $unpack_debug_enabled and $do_diagnostic = true;
$log_file = '/tmp/errors.log'; 

but I cannot find the logs being created. Feel like i'm missing something really obvious? I've checked all folder permissions, even 777'd them, still nothing. Anyone have any hints for me?! at my wits end!
