### ISSUE TITLE
Delete Key does not prompt a "Remove Torrent" confirmation, even with the option checked in.

### ISSUE THREAD

**Issue by Pabsilon** [Novik/ruTorrent#2596]
### Please complete the following tasks.

- [X] Web browser cache cleared
- [X] Link provided to install script if applicable
- [X] Not using broken rtinst install script
- [X] Web browser, ruTorrent, PHP and OS version provided

### Tell us about your environment

Web Broser: Brave 1.60.114
ruTorrent v4.2.6
OS: Debian Bulseye | 5.10.0-26

### Tell us how you installed ruTorrent

I'm running ruTorrent next to rTorrent in the crazymax docker container

### Describe the bug

When pressing delete with a torrent selected, the .torrent file and the downloaded files are deleted without a confirmation box. This happens even with the "Confirm when deleting torrents" option checked.

This does not happen when using the top menu bar, and it doesn't happen when using the right click menu provided with the Deletedata plugin.

### Steps to reproduce

1. Select a torrent from the list
2. Press the 'Del' key on your keyboard
3. Your torrent has been deleted without confirmation

### Expected behavior

The confirmation box with "Remove Torrent(s) : Do you really want to remove the selected torrent(s)?" should be shown before deleting.

**Comment by stickz** [comment]
I labeled this as an enhancement. We can add an option to display a confirmation box, when using the delete key on `v4.2`. It needs to be a separate option though and I think it should be disabled by default.

**Comment by FunThomas76** [comment]
i have the same problem, with very old version 4.0.2 it works fine and the setting for confirmation dialog for delete works as expected and in 4.2.8 it does not matter what the setting is it deletes without confirmation.
For me it is more secure to confirm -> since if you press delete you could maybe delete all torrents if you are in the wrong folder.

is it known which is the last version where this deletion confirmation dialog works?

**Comment by stickz** [comment]
@FunThomas76 Could you go to `Settings -> General` and see if `confirm when deleting torrents` is checked off?

**Comment by FunThomas76** [comment]
it saves the state under settings -> general -> confirm when deleting but checked or not checked makes here no difference
my first thought was that some config file had not the right file permissions but the state of the setting get saved but it does not change anything here

**Comment by stickz** [comment]
Resolved in v5.0 releasing shortly.

**Comment by FunThomas76** [comment]
The bug is back in my 5.1.5 :-(
switched the settings for confirmation dialog but nothing changed -> when mark a torrent and press DEL it does not ask for confirmation
